version: "3.8"
services:
  database:
    container_name: uptask-db
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    environment: 
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: uptask
    volumes:
      - ~/docker/db/uptask/v1.0/mysql:/var/lib/mysql
    ports: 
      - "3306:3306"
  server:
    container_name: uptask-app
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    links: 
      - database
    depends_on: 
      - database
    environment:
      WAIT_HOSTS: database:3306
      WAIT_BEFORE: 180
      WAIT_SLEEP_INTERVAL: 60
